### ISSUE TITLE
ffmpeg.ffplay : libGL error: MESA-LOADER: failed to open r600

### ISSUE THREAD

**Issue by boffo1** [snapcrafters/ffmpeg#38] opened 2019-07-17 07:48 UTC
After snap refreshed ffmpeg to revision 821 , this recurring problem has come up again.
Prior to that, every time snap did an revision upgrade, I would revert back to revision 775, which fixed the problem. But now 775 has gone from the repository, so I'm stuck with 834.
ffmpeg works, but ffmpeg.ffplay and ffmpeg.ffprobe do not .
All the suggestions on this website and others, have failed to fix the problem.

Using XUbuntu 18.04LTS

`x@x:~$ ffplay -version
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open r600 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: r600
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 156 (GLX)
  Request Minor code 6 ()
  Error Serial #60
  Current Serial #59
ffplay version n4.1.4 Copyright (c) 2003-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
`

**Comment by twosky2000** [comment] 2020-06-09 21:38
Duplicate of #42
I'm not sure that ffplay is supported.

**Comment by flexiondotorg** [comment] 2020-08-31 12:47
Fixed via 22c450921e2196e30068e1f736b3b01ba1fa3cac

**Closed by flexiondotorg** 2020-08-31 12:47 UTC
